### ISSUE TITLE
Voice chat fix makes my game crash on startup

### ISSUE THREAD

**Issue by Insidious849** [main-exe/UT2004-OpenAL#1]
![UT2004 OAL error](https://github.com/user-attachments/assets/6e130641-aa99-4cf3-af00-f8fe05d9e7f9)

Usually, it's fixed by starting the game again; most of the time, I have to repeatedly keep on rebooting the game, and it's really tedious. I will also post my .ini if it will be of any help:

[UT2004 ini.zip](https://github.com/user-attachments/files/16646762/UT2004.ini.zip)

**Comment by main-exe** [comment]
It is caused when **ALAudio.dll** can't resolve required DLLs, is missing from game's **System** folder or is corrupted.

**Comment by DarkBeemo** [comment]
My ALAudio.dll was completely unaltered, but I tried to use yours anyway; it still crashes me.

**Comment by main-exe** [comment]
Windows can mark downloaded files as blocked. 
Whole instructions ZIP might be blocked which could have resulted in included files being blocked after extraction too.

Right click on **UT2004-OpenAL-2023-11-08.zip** and unblock if it is blocked.
Extract it again and replace OpenAL DLLs in game's **System** folder.
![Unblock-file](https://github.com/user-attachments/assets/12c6f19b-54e0-4115-9d9c-0fbf28732c33)


Can double check each file individually that they are not blocked - **OpenAL32.dll**, **OpenAL64.dll**, ...

**Comment by Insidious849** [comment]
It still doesn't work.

**Comment by main-exe** [comment]
What happens if you delete **OpenAL32.dll** and  **OpenAL64.dll** from game's **System** folder?
Is game working then?

**Comment by Insidious849** [comment]
No.

**Comment by main-exe** [comment]
Then it has nothing to do with files from instructions ZIP. Game should have started normally.

You said at the beginning that restarting game fixes it sometimes. That makes it even weirder.

Could try to set back - **UseDefaultDriver=True** in **UT2004.ini**.
Though it seems that something else is corrupted. Try to reinstall game.

**Comment by Insidious849** [comment]
I fixed it; it turns out that DSOAL was causing the game to crash. You see, I didn't realize it at the time, but since *UT2004* already runs on OpenAL out of the box, it didn't need DSOAL, and so, the game was having a bad reaction to that. Thanks for your help, anyway!
